plugin_blacklist:
# common
- actuator_control
- ftp
- hil_controls
- global_position
- local_position
- manual_control
- safety_area
- setpoint_accel
- setpoint_attitude
- setpoint_position
- setpoint_raw
- setpoint_velocity
- vfr_hud
- waypoint
- hil
- battery
- battery2
- home_position
- estimator_status
- extended_state
- geofence
- nav_controller_output
- rallypoint
- setpoint_trajectory
- statustext
- wind_estimation
# extras
- altitude
- debug_value
- image_pub
- px4flow
- vibration
- vision_speed_estimate
- wheel_odometry

plugin_whitelist: []
#- 'sys_*'
